### ISSUE TITLE
Causing error in webpack profile output

### ISSUE THREAD

**Issue by jcontonio** [fqborges/webpack-fix-style-only-entries#14]
Running `webpack --profile --json` generates a JSON file with webpack-fix-style-only-entries output at the top

```
webpack-fix-style-only-entries: removing js from style only module: js/index.46b1fb85fc0ced7d86a7.js
{
  "errors": [],
  "warnings": [
```

**Comment by fqborges** [comment]
I couldn't reproduce. Are you using the latest version?

On #10 the output was changed to console.error as webpack recommends to avoid this type of issue.

**Comment by jcontonio** [comment]
Fixed in the latest version
