### ISSUE TITLE
miniCssExtractPlugin && browsersync - help needed

### ISSUE THREAD

**Issue by 7iomka** [fqborges/webpack-fix-style-only-entries#15]
Hello my dear friend.
I switched from 3 to 4 versions of the webpack, and have problems reloading the page using the browsersync (as standalone package, not webpack plugin) after I make changes to the style file. I found out about this plugin [here](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/151#issuecomment-414739879). I shot a separate video with a demonstration of my software environment.
https://cl.ly/73e1a91d894f
Please tell me why your plugin does not help me solve the problem? Maybe I did something wrong or did not understand what exactly your plugin does? I will be grateful for any help!

**Comment by 7iomka** [comment]
Note: extract-text-webpack-plugin on webpack 4 while it still works, and everything works as it should (except for the fact that all chunks are always generated), but it is not an option to use an outdated plugin :disappointed: 
Demo https://cl.ly/d8eb8d65604c

**Comment by fqborges** [comment]
It think this plugin does not solve your issue. It just find js files from chunks of css only entries and remove the js file from the compilation.
