### ISSUE TITLE
Does not delete js files...

### ISSUE THREAD

**Issue by smac89** [fqborges/webpack-fix-style-only-entries#16]
This is my config:

```js
const config = {
    target: "web",
    entry: {
        vendor: [
            'js/bootstrap.js',
            'js/classie.js',
            'js/html5element.js',
            'js/html5shiv.js',
            'js/jquery.1.8.3.min.js',
            'js/jquery.easing.1.3.js',
            'js/jquery.isotope.js',
            'js/jquery-scrolltofixed.js',
            'js/respond-1.1.0.min.js',
            'js/wow.js',

            'css/animate.css',
            'css/bootstrap.css',
            'css/font-awesome.css',
            'css/linecons.css',
            'css/responsive.css',
        ],
        style: ['css/style.css']
    },
    output: {
        publicPath: "/files/",
        path: path.resolve(__dirname, 'public/files'),
        filename: '[name].js',
    },
    devServer: { // https://webpack.js.org/configuration/dev-server
        port: 4444,
        progress: true,
        writeToDisk: true,
    },
    devtool: "source-map",
    plugins: [
        new CleanWebpackPlugin(),
        new FixStyleOnlyEntriesPlugin(),
        new MiniCssExtractPlugin({
            filename: '[name].css'
        }),
    ],
    module: {
        rules: [
            {
                test: /\.html$/,
                use: [
                    'extract-loader',
                    {
                        loader: 'html-loader',
                        options: {
                            // minimize: true,
                            interpolate: true,
                            attrs: ["img:src", "link:href"]
                        }
                    },
                ]
            },
            {
                test: /\.(png|jpe?g|gif)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            outputPath: 'images/',
                            name: '[name].[ext]'
                        }
                    }
                ]
            },
            {
                test: /\.(woff2?|ttf|eot|svg)(\?.*?)?$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            outputPath: 'fonts/',
                            name: '[name].[ext]'
                        }
                    },
                ]
            },
            {
                test: /\.js$/,
                use: 'babel-loader',
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                        options: {
                            hmr: false
                        }
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true
                        }
                    }
                ]
            }
        ]
    },
    resolve: {
        modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    },
    resolveLoader: {
        moduleExtensions: ['-loader']
    }
};
```

After running webpack-dev-server, the files are generated and the css and js files for the `style` entry is still there

**Comment by fqborges** [comment]
Thanks for reporting this.

Sorry, but I do not usually use webpack-dev-server because it does not if well with my backend.

Could you please send me a minimum reproducible example of the problem, so I can make a test and fix it?

**Comment by petrloukota** [comment]
Hi, version 0.3.1 works fine, but version 0.4.0 does not work at all - JS files for each CSS file are still present.

**Comment by fqborges** [comment]
@petrloukota You mean for webpack-dev-server?

**Comment by vadymmasiuk** [comment]
Also, was trying to use. Unfortunately it's working only for production mode. In case of using on development stage, still *.js file produced. But for production it's just working as expected.
Any suggestion?
Development config: 
`const path = require('path');
const FixStyleOnly = require('webpack-fix-style-only-entries');
const MiniCssExtract = require('mini-css-extract-plugin');

module.exports = {
    entry: {
        script: './src/js/index.js',
        style: [
            './src/css/style.css',
            './src/scss/index.scss'
        ]
    },
    output: {
        filename: 'js/[name].js',
        publicPath: '/assets',
        path: path.resolve(__dirname, './../../www/assets/')
    },
    devtool: 'source-map',
    module: {
        rules: [
            {
                test: /\.(cs|sas|scs)s$/i,
                exclude: '/(node_modules|bower_components)/',
                use: [
                    MiniCssExtract.loader,
                    'css-loader',
                    { loader: 'sass-loader', options: {
                        sassOptions: {
                            indentWidth: 4,
                            outputStyle: 'expanded'
                        }, }, }
                ]
            }
        ]
    },
    plugins: [
        new FixStyleOnly(),
        new MiniCssExtract({
            filename: 'css/[name].css',
            chunkFilename: '[id].css',
        })
    ],
    devServer: {
        host: 'domain.com',
        port: 8080,
        contentBase: '../www',  //source of static assets
        index: '', // must be specified to enable root proxying
        proxy: {
            context: () => true,
            target: 'http://domain.com/'
        },
        //stats: 'errors-only',
        overlay: true
    }
}`

**Comment by fqborges** [comment]
tried version 0.5.0?

**Comment by vadymmasiuk** [comment]
> tried version 0.5.0?

Yes, actually this is the version I'm trying.
Here is my simple package.json
`<pre>
{
    "name": "domain.com",
    "version": "0.0.1",
    "private": true,
    "description": "Some description",
    "comment": "1",
    "main": "index.js",
    "scripts": {
        "dev": "webpack-dev-server --open --mode development --config ./cfg/webpack.dev.config.js",
        "build": "webpack --mode production --config ./cfg/webpack.prod.config.js"
    },
    "keywords": [],
    "author": "Admin <admin@domain.com>",
    "license": "MIT",
    "browserslist": [
        "> 1%",
        "last 3 version"
    ],
    "devDependencies": {
        "@babel/core": "^7.9.6",
        "@babel/preset-env": "^7.9.6",
        "babel-loader": "^8.1.0",
        "css-loader": "^3.5.3",
        "mini-css-extract-plugin": "^0.9.0",
        "node-sass": "^4.14.1",
        "path": "^0.12.7",
        "sass-loader": "^8.0.2",
        "webpack": "^4.41.2",
        "webpack-cli": "^3.3.11",
        "webpack-dev-server": "^3.11.0",
        "webpack-fix-style-only-entries": "^0.5.0"
    },
    "dependencies": {
    }
}
</pre>`

**Comment by fqborges** [comment]
Well, I answered without paying attention to the actual issue. <o>

I don't think webpack-dev-server works the same as a webpack regular build. Probably something similar to webpack-hot-middleware.

See: 
 - https://github.com/fqborges/webpack-fix-style-only-entries#i-use-webpack-hot-middleware
 - https://github.com/fqborges/webpack-fix-style-only-entries/issues/12
 - https://github.com/fqborges/webpack-fix-style-only-entries/blob/master/test/cases/css-entry-with-ignored-hmr/webpack.config.js

**Comment by vadymmasiuk** [comment]
> Well, I answered without paying attention to the actual issue.
> 
> I don't think webpack-dev-server works the same as a webpack regular build. Probably something similar to webpack-hot-middleware.
> 
> See:
> 
> * https://github.com/fqborges/webpack-fix-style-only-entries#i-use-webpack-hot-middleware
> * #12
> * https://github.com/fqborges/webpack-fix-style-only-entries/blob/master/test/cases/css-entry-with-ignored-hmr/webpack.config.js

Ok, got it, and thanks for quick response. That was actually similar problem to what you have mentioned.
Just in case somebody will face similar issue, plugin must be with passed ignoring option, like next:
`{
plugins: [
        new FixStyleOnlyEntriesPlugin({ ignore: 'webpack-dev-server' }),
        new MiniCssExtract({
            filename: 'css/[name].css',
            chunkFilename: '[id].css',
        })
    ],
}`

**Comment by fqborges** [comment]
solved!
