### ISSUE TITLE
Handle .mjs extension removal from style only entry

### ISSUE THREAD

**Issue by matteobad** [fqborges/webpack-fix-style-only-entries#20]
As of right now the plugin will only remove the corresponding .js file. When bundling using the module .mjs extension this plugin won't work.

I would gladly make a PR if you think this feature can be useful. Just let me know.

**Comment by fqborges** [comment]
I am fully open for PRs, thanks a lot.

hint: https://github.com/fqborges/webpack-fix-style-only-entries/blob/master/index.js#L33

**Comment by matteobad** [comment]
Hi @fqborges, thanks for the hint. I've opened a PR with the feature, some tests an a minor version bump. Let me know if something is not right or can be improved.
