### ISSUE TITLE
Does not remove style only entries when running webpack in watch mode

### ISSUE THREAD

**Issue by eloiqs** [fqborges/webpack-fix-style-only-entries#24]
The plugin is not removing style only entries on subsequent compilation when running webpack in watch mode. The first run goes fine, but then it runs into issues with the `_collectedModules` cache.

https://github.com/fqborges/webpack-fix-style-only-entries/blob/7557e38a8cbb237d8b8948e2129442547b36e903/index.js#L69-L72

The first run will have already pushed the style only entries into it, and it will return an empty list for the resources of the module, it will then not be considered a style only module. 

Would you consider reseting `_collectedModules` on every watch? Or maybe improving this cache to contain whether the module is style only (or not)?

**Comment by fqborges** [comment]
clearing collectedModules on watch on 0.5.0
