### ISSUE TITLE
Wrong JS  file is removed.

### ISSUE THREAD

**Issue by zhangyuliangzyl** [fqborges/webpack-fix-style-only-entries#29]
Hello fqborges,
Thaks for your plugin, it's very helpful. But it seems something wrong in new webpack version.

I have the webpack entry 
```
entry: {
    main/modules/footer': '/xxx/src/pages/main/modules/footer/index.js',
    cssAssets/open/common/footer': '/xxx/src/pages/open/common/assets/css/footer.less',
    'open/modules/footer': '/xxx/src/pages/open/modules/footer/index.js',
    'testnet/modules/footer': '/xxx/src/pages/testnet/modules/footer/index.js',
}
```
It can work as I want before when I use webapck 4.10.2.

I upgrade my webpack to version 4.43.0 recently, something is wrong. All of the file like '/footer/index.js' is removed. I just want remove the extra js file when the entry is less/css.
Any idea to fix it ?

**Comment by fqborges** [comment]
It should be the same problem as #23, fixed on 0.5.0
