### ISSUE TITLE
Webpack 5 warnings

### ISSUE THREAD

**Issue by matteobad** [fqborges/webpack-fix-style-only-entries#31]
Hi @fqborges, thank you for the great work. I was wondering if you plan to update this plugin to support Webpack 5. I'm trying to integrate it into some work project and there are some deprecation warnings.

To be more specific:
```sh
(node:12688) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
(node:12688) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
(node:12688) [DEP_WEBPACK_MODULE_INDEX] DeprecationWarning: Module.index: Use new ModuleGraph API
(node:12688) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'filter' is deprecated)
```

I can help with the upgrade if needed. Let me know and thank you in advance.

**Comment by fqborges** [comment]
As far as I know, webpack 5 does not generate the empty js for css entries. 

see: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85#issuecomment-582880948
There is also PR I can't find right now.

**Comment by matteobad** [comment]
This is very interesting. I tried today with the latest beta.16 and I still have the empty JS without this plugin... so I guess we will have to wait until the official release

**Comment by LeSuisse** [comment]
Hi,

From what I gather from here https://github.com/webpack/webpack/issues/11088#issuecomment-653117145 it looks like this plugin will still be useful with Webpack 5 :disappointed:

**Comment by fqborges** [comment]
@LeSuisse  Thanks for the info.

**Comment by webdiscus** [comment]
Hi @matteobad, @fqborges I have fixed Webpack 5 deprecation messages (like DEP_WEBPACK_...) and fixed some integration tests. Now all Integration tests pass with Webpack 5.1.3.

See my PR: https://github.com/fqborges/webpack-fix-style-only-entries/pull/40
For usage with Webpack 5 you can try my fork: webdiscus/webpack-fix-style-only-entries

**Comment by kuworking** [comment]
When using the plugin I see `Module.entryModule: Multiple entry modules are not supported by the deprecated API (Use the new ChunkGroup API)`

```
"webpack": "5.4.0",
"webpack-fix-style-only-entries": "^0.6.0",
```

As suggested, If using https://github.com/webdiscus/webpack-remove-empty-scripts there's no error and the plugin works

**Comment by ankurk91** [comment]
https://github.com/fqborges/webpack-fix-style-only-entries/pull/43

**Comment by bigskillet** [comment]
Confirming that Webpack 5 is still creating the extra js file and also confirming the deprecation warning.

**Comment by fqborges** [comment]
The current package version is not compatible with webpack 5. There is a fork here that is compatible: https://github.com/webdiscus/webpack-remove-empty-scripts
