### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by jens-duttke** [fqborges/webpack-fix-style-only-entries#32]
Would it be possible to give a short overview over the changes you did, either on the Releases page:
https://github.com/fqborges/webpack-fix-style-only-entries/releases
or in a separate CHANGELOG.md?

If you have to manage large projects with dozens of dependencies it's very time-consuming to track breaking changes of all your dependencies and get an overview of new features provided in new versions without a changelog.

I understand that my request may sound a bit egoistic - asking you to investigate more time, so that I can save time - but it's not meant that way.
Your extension is very useful and I'm very thankful that you've used your time to release that to the public, so that I (and many others) can benefit from it. A changelog which allows to track changes would just be a great improvement for your users. ;-)

**Comment by fqborges** [comment]
Yes, makes sense, I will do that when possible.

Fyi, the change from 0.4.0 to 0.5.0:
 - fix for #23 (https://github.com/fqborges/webpack-fix-style-only-entries/commit/37d350eec83f49c0b12729a93aa6cf2f96d92d0b)
 - fix for #24 (https://github.com/fqborges/webpack-fix-style-only-entries/commit/d92bec4be5fe4b97a8651a9206fa2281ce1424be)
 - [BREAKING] added styl and sass to default extensions (https://github.com/fqborges/webpack-fix-style-only-entries/commit/247a5c9f963e4d7598539056ab3f709b0558b4ec)
 - added LICENSE.txt (https://github.com/fqborges/webpack-fix-style-only-entries/commit/220e20eeb9bc95652a942812a424aadd92ec7d1f)

**Comment by matteobad** [comment]
It could be useful to automate the releases and CHANGELOG with something like semantic-release and a CI. If you are interested I could help set it up. Keep up the good work|

**Comment by fqborges** [comment]
added in https://github.com/fqborges/webpack-fix-style-only-entries/commit/3e3767d8998a53d807b5d5b10643d05b800aa79a
