### ISSUE TITLE
option "default"  listed in the readme is not correct

### ISSUE THREAD

**Issue by aaarichter** [fqborges/webpack-fix-style-only-entries#4]
according to the code 
https://github.com/fqborges/webpack-fix-style-only-entries/blob/master/index.js#L4 it should be "extensions" instead of "default"

**Comment by fqborges** [comment]
Actually the name in readme is extensions:
https://github.com/fqborges/webpack-fix-style-only-entries/blame/master/README.md#L56 
But I see the confusion. Going to change it soon.

**Comment by fqborges** [comment]
updated readme to make it clear
