### ISSUE TITLE
Continuous alert that its "removing" the file on webpack --watch

### ISSUE THREAD

**Issue by btassone** [fqborges/webpack-fix-style-only-entries#5]
Image of the problem: https://imgur.com/a/4XdxYQ8
Command ran: webpack --env development --watch

I'd rather not suppress alerts because I have to believe there is a better solution that can be done.

**Comment by fqborges** [comment]
Thanks for reporting! It happens because you saved a file but the compilation didn't change, right? I will try to figure out how to detect this case, similar how the watch output is doing.

**Comment by btassone** [comment]
Yup haven't changed anything I just start watch and it keeps spitting that out.

Also had to switch to a different webpack plugin because when running for a different directory it wasn't able to find the module for some reason. Not quite sure what was going on their either.

**Comment by fqborges** [comment]
> 
> Yup haven't changed anything I just start watch and it keeps spitting that out.

Well, for some reason, something was updating the compilation frequently, so the list of messages. Not that it diminishes the bug.

> 
> Also had to switch to a different webpack plugin because when running for a different directory it wasn't able to find the module for some reason. Not quite sure what was going on their either.

A plugin for solving this same issue: empty js for style only modules? I would love join efforts with someone else.
