### ISSUE TITLE
Add `exclude` and/or `include` options

### ISSUE THREAD

**Issue by mikeselander** [fqborges/webpack-fix-style-only-entries#7]
It would be very handy to have an exclusion and/or inclusion list for parsing file strings. This would make parsing faster and more reliable and could help address issues where the script catches JS files it shouldn't.

This add-on is currently catching a JS file that it shouldn't (similar to #6), for reasons that I've yet to figure out. Although this fixes the problem in the wrong place, this would allow one to skirt past this and also to make the script only run where necessary.

**Comment by fqborges** [comment]
I am overburden by work, but will try to do something later.

 - https://github.com/fqborges/webpack-fix-style-only-entries/blob/master/index.js#L38 match modules resources for chunk, can exclude/include chunk by checking the option here.
 - https://github.com/fqborges/webpack-fix-style-only-entries/blob/master/index.js#L42 match the '.js' file can exclude/include file checking the option here.

As always, PR are welcome. 🤙

About the bug on #6, unfortunately I did not found this problem yet. Could you share a reproducible example?

**Comment by fqborges** [comment]
The new ignore option on v0.3.0 should do the work.

see: https://www.npmjs.com/package/webpack-fix-style-only-entries#i-use-webpack-hot-middleware
