### ISSUE TITLE
Removes required JS files too

### ISSUE THREAD

**Issue by nnx0r** [fqborges/webpack-fix-style-only-entries#9]
Hi there,

I started using your webpack plugin in Vue CLI 3 (config file) a while ago. 
I did not have any problems when I tried to build the project, but I noticed that I had issues with my configuration where app would be injected before vendor files and code did not work properly this way.

---

I had to modify my configuration file and then your plugin stopped working properly.

**Old configuration: (your plugin works)**

```
const FixStyleOnlyEntries = require('webpack-fix-style-only-entries')

module.exports = {
  chainWebpack: config => {
    config
      .entry('vendor')
        .add('./src/assets/styles/vendor.scss')
      .end()
      .entry('app')
        .add('./src/assets/styles/app.scss')
      .end()
      .plugin('html')
      .tap(args => {
        args[0].title = process.env.VUE_APP_TITLE
        return args
      })
  },

  configureWebpack: {
    plugins: [
      new FixStyleOnlyEntries()
    ]
  }
}
```

**New configuration: (your plugin breaks)**

```
const FixStyleOnlyEntries = require('webpack-fix-style-only-entries')

module.exports = {
  chainWebpack: config => {
    config.entryPoints.delete('app')

    config
      .entry('vendor')
        .add('./src/assets/styles/vendor.scss')
      .end()
      .entry('app')
        .add('./src/main.js')
        .add('./src/assets/styles/app.scss')
      .end()
      .plugin('html')
      .tap(args => {
        args[0].title = process.env.VUE_APP_TITLE
        return args
      })
  },

  configureWebpack: {
    plugins: [
      new FixStyleOnlyEntries()
    ]
  }
}
```

As you can see, the only thing I'm doing is removing default `app` entry point and re-specifying it after vendor, along with my `app.scss` file.

If I throw `vue inspect` to see the actual webpack configuration, the part of entry points is looking like this:

```
entry: {
    vendor: [
      './src/assets/styles/vendor.scss'
    ],
    app: [
      './src/main.js',
      './src/assets/styles/app.scss'
    ]
}
```

Which is correct... However, when I run `npm run build` your plugin removes the `main.js` file from the build entirely.

I'd be greatful if you can fix this... I noted that you mentioned in #6 that it is solved in version 0.0.5, but it does not seem to be the case. I am using that exact version.

**Comment by dvlden** [comment]
Tested new update and now it is working properly.
Thank you for finding spare time to rework this and resolve the issues.

:heart:
